import { FrameColorOption, FrameDefinition } from '../types';

export const STANDARD_COLORS: FrameColorOption[] = [
  {
    id: 'midnight',
    name: 'Midnight Black',
    bodyColor: '#121316',
    rimColor: '#27292e',
    bezelColor: '#0a0a0c',
    accentHighlight: '#3c4048',
  },
  {
    id: 'titanium-natural',
    name: 'Natural Titanium',
    bodyColor: '#8f8a81',
    rimColor: '#b5afa6',
    bezelColor: '#1a1816',
    accentHighlight: '#ded9cf',
  },
  {
    id: 'silver',
    name: 'Silver / Starlight',
    bodyColor: '#e3e4e8',
    rimColor: '#f5f6f8',
    bezelColor: '#0d0e11',
    accentHighlight: '#ffffff',
  },
  {
    id: 'deep-purple',
    name: 'Deep Purple',
    bodyColor: '#362f44',
    rimColor: '#4f4464',
    bezelColor: '#0c0912',
    accentHighlight: '#746491',
  },
  {
    id: 'champagne-gold',
    name: 'Champagne Gold',
    bodyColor: '#d6c8b0',
    rimColor: '#ede2ce',
    bezelColor: '#16130d',
    accentHighlight: '#fff8eb',
  },
  {
    id: 'cosmic-black',
    name: 'Space Gray',
    bodyColor: '#282a2e',
    rimColor: '#454850',
    bezelColor: '#0a0a0b',
    accentHighlight: '#5e636e',
  },
];

export const FRAME_DEFINITIONS: FrameDefinition[] = [
  {
    id: 'phone-dynamic-island-portrait',
    name: 'Dynamic Pill (Portrait)',
    cutoutStyle: 'dynamic-island',
    orientation: 'portrait',
    aspectRatio: 9 / 19.5, // ~1179 x 2556
    outerWidth: 900,
    outerHeight: 1860,
    bezelThickness: 28,
    outerCornerRadius: 92,
    screenBounds: {
      x: 28,
      y: 28,
      width: 844,
      height: 1804,
      borderRadius: 72,
    },
    cutout: {
      type: 'dynamic-island',
      x: 337, // Center pill
      y: 52,
      width: 226,
      height: 60,
      radius: 30,
    },
    availableColors: STANDARD_COLORS,
    defaultColorId: 'midnight',
  },
  {
    id: 'phone-dynamic-island-landscape',
    name: 'Dynamic Pill (Landscape)',
    cutoutStyle: 'dynamic-island',
    orientation: 'landscape',
    aspectRatio: 19.5 / 9,
    outerWidth: 1860,
    outerHeight: 900,
    bezelThickness: 28,
    outerCornerRadius: 92,
    screenBounds: {
      x: 28,
      y: 28,
      width: 1804,
      height: 844,
      borderRadius: 72,
    },
    cutout: {
      type: 'dynamic-island',
      x: 52,
      y: 337,
      width: 60,
      height: 226,
      radius: 30,
    },
    availableColors: STANDARD_COLORS,
    defaultColorId: 'midnight',
  },
  {
    id: 'phone-punch-hole-portrait',
    name: 'Punch Hole Center (Portrait)',
    cutoutStyle: 'punch-hole',
    orientation: 'portrait',
    aspectRatio: 9 / 20, // ~1080 x 2400
    outerWidth: 900,
    outerHeight: 1900,
    bezelThickness: 22,
    outerCornerRadius: 84,
    screenBounds: {
      x: 22,
      y: 22,
      width: 856,
      height: 1856,
      borderRadius: 66,
    },
    cutout: {
      type: 'punch-hole',
      x: 432,
      y: 54,
      width: 36,
      height: 36,
      radius: 18,
    },
    availableColors: STANDARD_COLORS,
    defaultColorId: 'titanium-natural',
  },
  {
    id: 'phone-punch-hole-landscape',
    name: 'Punch Hole (Landscape)',
    cutoutStyle: 'punch-hole',
    orientation: 'landscape',
    aspectRatio: 20 / 9,
    outerWidth: 1900,
    outerHeight: 900,
    bezelThickness: 22,
    outerCornerRadius: 84,
    screenBounds: {
      x: 22,
      y: 22,
      width: 1856,
      height: 856,
      borderRadius: 66,
    },
    cutout: {
      type: 'punch-hole',
      x: 54,
      y: 432,
      width: 36,
      height: 36,
      radius: 18,
    },
    availableColors: STANDARD_COLORS,
    defaultColorId: 'titanium-natural',
  },
  {
    id: 'phone-notch-portrait',
    name: 'Classic Notch (Portrait)',
    cutoutStyle: 'notch',
    orientation: 'portrait',
    aspectRatio: 9 / 19.5,
    outerWidth: 900,
    outerHeight: 1860,
    bezelThickness: 30,
    outerCornerRadius: 90,
    screenBounds: {
      x: 30,
      y: 30,
      width: 840,
      height: 1800,
      borderRadius: 68,
    },
    cutout: {
      type: 'notch',
      x: 310,
      y: 30,
      width: 280,
      height: 56,
      radius: 20,
    },
    availableColors: STANDARD_COLORS,
    defaultColorId: 'midnight',
  },
  {
    id: 'phone-waterdrop-portrait',
    name: 'Waterdrop Curve (Portrait)',
    cutoutStyle: 'waterdrop',
    orientation: 'portrait',
    aspectRatio: 9 / 20,
    outerWidth: 900,
    outerHeight: 1880,
    bezelThickness: 24,
    outerCornerRadius: 80,
    screenBounds: {
      x: 24,
      y: 24,
      width: 852,
      height: 1832,
      borderRadius: 64,
    },
    cutout: {
      type: 'waterdrop',
      x: 422,
      y: 24,
      width: 56,
      height: 48,
      radius: 24,
    },
    availableColors: STANDARD_COLORS,
    defaultColorId: 'silver',
  },
  {
    id: 'phone-minimal-bezel-portrait',
    name: 'Minimal Bezel / Seamless (Portrait)',
    cutoutStyle: 'bezel-minimal',
    orientation: 'portrait',
    aspectRatio: 9 / 19.5,
    outerWidth: 900,
    outerHeight: 1860,
    bezelThickness: 24,
    outerCornerRadius: 82,
    screenBounds: {
      x: 24,
      y: 24,
      width: 852,
      height: 1812,
      borderRadius: 64,
    },
    cutout: {
      type: 'none',
      x: 0,
      y: 0,
      width: 0,
      height: 0,
    },
    availableColors: STANDARD_COLORS,
    defaultColorId: 'midnight',
  },
  {
    id: 'tablet-modern-portrait',
    name: 'Pro Tablet (Portrait)',
    cutoutStyle: 'tablet-modern',
    orientation: 'portrait',
    aspectRatio: 3 / 4,
    outerWidth: 1200,
    outerHeight: 1600,
    bezelThickness: 42,
    outerCornerRadius: 60,
    screenBounds: {
      x: 42,
      y: 42,
      width: 1116,
      height: 1516,
      borderRadius: 36,
    },
    cutout: {
      type: 'punch-hole',
      x: 590,
      y: 18,
      width: 20,
      height: 20,
      radius: 10,
    },
    availableColors: STANDARD_COLORS,
    defaultColorId: 'cosmic-black',
  },
  {
    id: 'tablet-modern-landscape',
    name: 'Pro Tablet (Landscape)',
    cutoutStyle: 'tablet-modern',
    orientation: 'landscape',
    aspectRatio: 4 / 3,
    outerWidth: 1600,
    outerHeight: 1200,
    bezelThickness: 42,
    outerCornerRadius: 60,
    screenBounds: {
      x: 42,
      y: 42,
      width: 1516,
      height: 1116,
      borderRadius: 36,
    },
    cutout: {
      type: 'punch-hole',
      x: 790,
      y: 18,
      width: 20,
      height: 20,
      radius: 10,
    },
    availableColors: STANDARD_COLORS,
    defaultColorId: 'cosmic-black',
  },
];

export function getFrameById(id: string): FrameDefinition {
  const found = FRAME_DEFINITIONS.find((f) => f.id === id);
  return found || FRAME_DEFINITIONS[0];
}

export function getFramesByCutout(style: string): FrameDefinition[] {
  return FRAME_DEFINITIONS.filter((f) => f.cutoutStyle === style);
}
