import { ExportPreset } from '../types';

export const EXPORT_PRESETS: ExportPreset[] = [
  {
    id: 'preset-original',
    name: 'Auto / Match Display (1920 × 1080)',
    category: 'custom',
    width: 1920,
    height: 1080,
    scaleFactor: 1,
  },
  {
    id: 'preset-ig-square',
    name: 'Instagram Post (1080 × 1080)',
    category: 'social',
    width: 1080,
    height: 1080,
    scaleFactor: 1,
  },
  {
    id: 'preset-ig-story',
    name: 'Instagram Story / TikTok (1080 × 1920)',
    category: 'social',
    width: 1080,
    height: 1920,
    scaleFactor: 1,
  },
  {
    id: 'preset-twitter-card',
    name: 'Twitter / X Post (1200 × 675)',
    category: 'social',
    width: 1200,
    height: 675,
    scaleFactor: 1,
  },
  {
    id: 'preset-product-hunt',
    name: 'Product Hunt Gallery (1270 × 760)',
    category: 'social',
    width: 1270,
    height: 760,
    scaleFactor: 1,
  },
  {
    id: 'preset-dribbble',
    name: 'Dribbble Shot (1600 × 1200)',
    category: 'social',
    width: 1600,
    height: 1200,
    scaleFactor: 1,
  },
  {
    id: 'preset-appstore-67',
    name: 'App Store 6.7" iPhone (1290 × 2796)',
    category: 'store',
    width: 1290,
    height: 2796,
    scaleFactor: 1,
  },
  {
    id: 'preset-playstore',
    name: 'Google Play Store (1080 × 2400)',
    category: 'store',
    width: 1080,
    height: 2400,
    scaleFactor: 1,
  },
  {
    id: 'preset-tablet-store',
    name: 'Tablet App Store (2048 × 2732)',
    category: 'store',
    width: 2048,
    height: 2732,
    scaleFactor: 1,
  },
];
